apiVersion: v1
kind: Secret
metadata:
  name: doc-collection-secrets
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://prathamai112005_db_user:apple@cluster0.up5ndfq.mongodb.net/doc_collection_db?retryWrites=true&w=majority"
  jwt-secret: "paperflow-secure-jwt-secret-key-2024"
